#!/bin/bash
# DANVERSE-X — Session Start Hook
# Injects project context at the start of every Claude Code session

echo "╔══════════════════════════════════════════════════════╗"
echo "║              DANVERSE-X  SESSION START               ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "📍 Branch:      $(git branch --show-current 2>/dev/null || echo 'unknown')"
echo "📝 Last commit: $(git log -1 --oneline 2>/dev/null || echo 'no commits')"
echo "📁 Changed:     $(git status --short 2>/dev/null | wc -l | tr -d ' ') files"
echo ""
echo "🌐 Stack: Next.js 15 | TypeScript strict | Tailwind | GSAP 3.14 | Three.js r169 | Lenis 1.3"
echo "🚀 Deploy: Netlify ONLY — output: export — never Vercel"
echo "🎨 Colors: Citrus #E0E75B | Teal #00A6A6 | Coral #EF786A | Lavender #C48BB4"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━ COMMANDS ━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  /commit             Smart conventional commit + emoji"
echo "  /create-pr          Branch + commit + open PR"
echo "  /pr-review \$PR      5-perspective code review"
echo "  /fix-github-issue N Fix GitHub issue #N"
echo "  /todo               Manage todos.md"
echo "  /context-prime      Deep prime context window"
echo "  /release \$VERSION   Tag + publish release"
echo "  /security-audit     Full security scan"
echo "  /performance-check  Bundle + CWV audit"
echo "  /deploy-check       Pre-deploy readiness"
echo "  /new-component \$N   Scaffold component"
echo "  /review-code        Post-change quality review"
echo "  /session-notes      Write session summary"
echo "  /video-prompt \$B    Cinematic AI video prompt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━ AGENTS ━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  code-reviewer       Bugs, TS, security, perf"
echo "  ui-architect        Component + layout design"
echo "  performance-auditor Bundle + CWV pre-deploy"
echo "  debug-specialist    Systematic error diagnosis"
echo "  prompt-engineer     AI video prompt writing"
echo "  security-auditor    Vulnerability deep-dive"
echo "  test-engineer       Write unit + E2E tests"
echo "  accessibility-expert WCAG 2.1 AA compliance"
echo "  git-master          Rebase, bisect, release"
echo "  seo-optimizer       Metadata + schema + sitemap"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━ SKILLS ━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Auto-loaded: design-system | nextjs | typescript | gsap | three.js"
echo "  Auto-loaded: framer-motion | arabic-rtl | a11y | security | git"
echo "  Auto-loaded: testing | performance | seo | cinematic-prompts"
echo ""
echo "💡 /context-prime for a full codebase briefing | AGENTS.md for Codex/Copilot"
echo ""
